[package]
name = "photo-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
photo-sync-core.workspace = true
photo-sync-protocol.workspace = true
rcgen.workspace = true
serde.workspace = true
thiserror.workspace = true
toml = { version = "0.9", features = ["parse"] }
rustls.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
x509-parser.workspace = true
refinery.workspace = true
rusqlite.workspace = true
rustix.workspace = true
mdns-sd = "0.21"
zbus = "5"

[lints]
workspace = true

[dev-dependencies]
photo-sync-sim.workspace = true
